### ISSUE TITLE
Wrong package name

### ISSUE THREAD

**Issue by IProSoft** [daothanh/asgard-taxonomy#2]
It can't be installed because name is not "taxonomy" but "asgard-taxonomy" :-)

**Comment by daothanh** [comment]
You can install via Composer:
`composer require daothanh/taxonomy`
`php artisan module:migrate Taxonomy`

## Add Routes
Go to reosources/assets/js/app.js

Import Routes: `import TaxonomyRoutes from '../../../Modules/Taxonomy/Assets/js/TaxonomyRoutes';`
Add TaxonomyRoutes to router: `...TaxonomyRoutes,`
Build webpack by `npm run dev`
Set permissions for your role

**Comment by IProSoft** [comment]
Thanks for reply. 
I can't install by composer because of requirements, I wanted to use "asgard:download:module" but it won't find package.
