### ISSUE TITLE
taxonomy->terms not show up

### ISSUE THREAD

**Issue by Arielblues** [daothanh/asgard-taxonomy#3]
hi i installed your package through composer.

composer require daothanh/taxonomy
php artisan module:migrate Taxonomy
and added the lines to reosources/assets/js/app.js

import TaxonomyRoutes from '../../../Modules/Taxonomy/Assets/js/TaxonomyRoutes';: ...TaxonomyRoutes,

and build the webpack  by npm run dev. 

i can see the taxonomy vocabulary in the admin and add and delete that. but i don't see the terms. anywhere (i set the rights correctly in th admin.)

when i try to go to terms by the link en/backend/taxonomy/terms i get 

Modules \ Core \ Foundation \ Asset \ AssetNotFoundException
No message

please advice.
i have a fresh install of asgard cms 3.6.1 and other nmodules like the blogmodule works fine.

**Comment by daothanh** [comment]
To show the category box in your form . You must use the TermsBox (a vuejs component) or taxonomyChooseTerms directive (with blade)

[TermsBox.vue](https://github.com/daothanh/taxonomy/blob/master/Assets/js/components/TermsBox.vue)

Example for page form:
```
<template>
<TermsBox vocabularyId="1" entity="Modules\Page\Entities\Page"/>
</template>

import TermsBox from '../../../../Taxonomy/Assets/js/components/TermsBox';`
export default {
        components: {TermsBox}
}
```
