### ISSUE TITLE
Module Folder Name Miss-match 

### ISSUE THREAD

**Issue by abid112** [daothanh/asgard-taxonomy#4]
After run the composer cmd, It creates the "AsgardTaxonomy" folder on Module folder. But when the migration run, It search for the "Taxonomy" folder on your module folder. So I think, You have to fix the name with only "Taxonomy"

**Comment by daothanh** [comment]
Yeb, You must rename  AsgardTaxonomy folder to Taxonomy then run ```php artisan module:migrate Taxonomy```
